### ISSUE TITLE
Low Code testing strategy for designs

### ISSUE THREAD

**Issue by chadell** [nautobot/nautobot-app-design-builder#168]
### Environment
* Nautobot version:  1.6.22
* nautobot-design-builder version:  1.3.0

### Proposed Functionality

Designs can be tested using unitest strategy as explained here: https://github.com/nautobot/nautobot-app-design-builder/blob/ltm-1.6/docs/user/design_testing.md

However, to make tests easier to develop, it would be convienient to expose a testing framework such as the one used internally: https://github.com/nautobot/nautobot-app-design-builder/blob/develop/nautobot_design_builder/tests/testdata/create_tags.yaml where the developer could define:

```yaml
---
design_job: "path to the job class"
input_data:
  "tag_name": Test Tag"
checks:
  - model_exists:
      model: "nautobot.extras.models.Tag"
      query: {name: "Test Tag"}
```

### Use Case

This would facilitate a lot new test creation
