### ISSUE TITLE
Devices assigned a rack position are not idempotent

### ISSUE THREAD

**Issue by austind** [nautobot/nautobot-app-design-builder#207]
### Environment
* Python version:  3.11.9
* Nautobot version:  v2.3.1
* nautobot-design-builder version:  2.1.0

### Expected Behavior
Design builder jobs that include devices which are assigned a rack position, while using `!create_or_update`, should not produce an error. They should update any out-of-sync properties as usual.

### Observed Behavior

The design builder job fails with a `DesignValidationError`. Example output:

```
Device test2-compute-1 failed validation

  **position:** U10 is already occupied or does not have sufficient space to accommodate this device type: my-test-devicetype (1U)
```

### Steps to Reproduce
1. Create a design builder job that includes at least one rack and one device assigned a position in the rack
2. Run the design job. This will succeed. 
3. Run the design job again with the same params. This will fail.

Example template snippet that produced the error above:

```yaml
    - "!create_or_update:name": "{{ name }}"
      location__name: "{{ location }}"
      device_type: "{{ device_type }}"
      role: "!ref:role"
      status__name: "{{ status }}"
      rack: "{{ rack }}"
      face: front
      position: "{{ position }}"
      "!ref": "{{ name }}"
```

Slack thread: https://networktocode.slack.com/archives/C01NWPK6WHL/p1738862632689189
