### ISSUE TITLE
[DOCS] Allow merging top-level list keys in included templates

### ISSUE THREAD

**Issue by austind** [nautobot/nautobot-app-design-builder#208]
### Environment
* Nautobot version:  2.4.2
* nautobot-design-builder version:  2.1.0

### Proposed Functionality

Add support for merging top-level lists from multiple YAML documents in included templates. When a template includes other templates using Jinja2's {% include %} statement, any top-level lists (like manufacturers, device_types, etc.) should be merged together, preserving all entries from each included template.
For example, if template A includes templates B and C:
```
# template_b.yaml
manufacturers:
    - name: "Manufacturer 1"

# template_c.yaml
manufacturers:
    - name: "Manufacturer 2"

# template_a.yaml
{% include 'template_b.yaml' %}
{% include 'template_c.yaml' %}
```
The resulting YAML should contain both manufacturers:
```
manufacturers:
    - name: "Manufacturer 1"
    - name: "Manufacturer 2"
```
"

### Use Case
This functionality allows design templates to be modular and reusable. Users can:
* Split large designs into smaller, focused templates
* Include common configurations from shared templates
* Keep related content types together in organized files

**Comment by itdependsnetworks** [comment]
Makes sense, how does it merge in relationship to other keys? e.g. if I have 

```yaml
# template_b.yaml
manufacturers:
    - name: "Manufacturer 1"

devices:
    - name: nyc-rt01

# template_c.yaml
manufacturers:
    - name: "Manufacturer 2"
```

what does it result in?

**Comment by austind** [comment]
```
manufacturers:
  - name: "Manufacturer 1"
  - name: "Manufacturer 2"
 
devices:
  - name: nyc-rt01
```

**Comment by abates** [comment]
Unfortunately, this is not something that can be easily implemented. The YAML loading portion of a template is done simply with pyyaml. The templates are rendered and then loaded. For example, including two templates that each have a `manufacturers` stanza will result in the following yaml:

```yaml
# template_b.yaml
manufacturers:
    - name: "Manufacturer 1"

# template_c.yaml
manufacturers:
    - name: "Manufacturer 2"
```

You can see the behavior with this simple python script:
```python
#!/usr/bin/env python3

import yaml
from pprint import pp

yaml_input = """
# template_b.yaml
manufacturers:
    - name: "Manufacturer 1"

# template_c.yaml
manufacturers:
    - name: "Manufacturer 2"
"""

data = yaml.safe_load(yaml_input)

pp(data)
# output:
# {'manufacturers': [{'name': 'Manufacturer 2'}]}
```

The second instance of `manufacturers` overwrites the first, it doesn't merge it. I'm not sure if pyyaml can be extended to allow merging of data structures. Technically, [YAML requires unique keys](https://yaml.org/spec/1.2.2/#node-comparison), so the above yaml is a spec violation.
