### ISSUE TITLE
Nautobot 2.0 support - IP Address fails

### ISSUE THREAD

**Issue by mzbroch** [nautobot/nautobot-app-design-builder#40]
### Environment
* Python version:  
* Nautobot version:  
* design-builder version:  

### Expected Behavior

IP Address creation works

### Observed Behavior

IP Address creation is not possbile with Nautobot 2.0 namespaces

### Steps to Reproduce
1.
2.
3.

**Comment by abates** [comment]
@mzbroch: is this fixed in #95?

**Comment by mzbroch** [comment]
I was able to use following format using design builder `0.4.4`
```
      - name: "Ethernet3"
        type: "1000base-t"
        status__name: "Active"
        enabled: True
        ip_address_assignments:
          - ip_address:
              "!create_or_update:address": "10.11.11.17/30"
              "!create_or_update:parent": "!ref:ntc_parent_prefix"
              status__name: "Active"
              tenant: "!ref:ntc_tenant"
```
