### ISSUE TITLE
Allow query by natural key.

### ISSUE THREAD

**Issue by abates** [nautobot/nautobot-app-design-builder#76]
### Environment
* Nautobot version:  Any
* design-builder version: latest

### Proposed Functionality
It is a very common pattern to have simple queries that are almost always utilizing a natural key lookup. For instance, the `Status` model is heavily used throughout Nautobot and is required on many models (devices, interfaces, sites, etc). This leads to quite a bit of repetition in Design Builder like so:

```yaml
sites:
- name: "New Site"
  status__name: "Active"
```

In this example, the `Status` object is being assigned by its name `Active`. It would be nice if design builder could auto-detect when the intent is to lookup by natural key so that the above code becomes:

```yaml
sites:
- name: "New Site"
  status: "Active"
```
